[build]
  base    = "/"
  publish = "/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  [[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
buildDir = "public"
